server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
   import:
    - "application_qa.yml"
    - "application_prod.yml"
  profiles:
   active:
    - "qa"


build:
  version: "3.0"

loans:
 message: "Welcome to AmitBank loans related local APIs "
 contactDetails:
  name: "Amit Mandal - Developer"
  email: "amit.mandal.2209@gmail.com"
 onCallSupport:
  - (91) 9315774030
  - (91) 0000000000