spring:
 application:
  name: "configServer"
 profiles:
  #active: native --> Use when you are using the classpath & file system reading
  active: git
 cloud:
  config:
   server:
    #native:
     #search-locations: "classpath:/config"
     #search-locations: "file:///D://config"
    git:
     uri: "https://github.com/AmitMandal16/amit-config.git"
     default-label: main
     timeout: 5
     clone-on-start: true
     force-pull: true

encrypt:
  key: "ED1F32DD15585C3A3DDFFCD8DACC8"
server:
 port: 8071