services:
 accounts:
  image: "amitmandal22/accounts:v1"
  container_name: accounts-ms
  ports:
  - "8081:8081"
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
   - amitbank
 loans:
  image: "amitmandal22/loans:v1"
  container_name: loans-ms
  ports:
  - "8090:8090"
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
   - amitbank
 cards:
  image: "amitmandal22/cards:v1"
  container_name: cards-ms
  ports:
  - "9000:9000"
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
   - amitbank
networks:
 amitbank:
  driver: "bridge"
   