build:
 version: "3.0"

cards:
 message: "Welcome to AmitBank cards related local APIs "
 contactDetails:
  name: "Amit Mandal - Developer"
  email: "amit.mandal.2209@gmail.com"
 onCallSupport:
  - (91) 9315774030
  - (91) 0000000000
