build:
 version: "2.0"

accounts:
 message: "Welcome to AmitBank accounts related QA APIs "
 contactDetails:
  name: "Amit Mandal - QA Lead"
  email: "amit.mandal.2209@gmail.com"
 onCallSupport:
  - (91) 9315774030
  - (91) 0000000000